### PR TITLE
Yields

### PR DESCRIPTION
**Pull request by sz16900**
# Completed [Project # 9 Bubble Sort](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks?ref=lnav) in partial requirements of the [Microverse Curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/).

---

### Contributors:
- Jose Fernandez Caminero
- Seth Zea

--- 

##### General Requirements

- [x] Add a descriptive README file to your repository.
- [x] Use meaningful names for your Pull Requests and add a short summary of its content.
- [x] Use descriptive commit messages.
- [x] Do not commit files that are not related to the project. Instead, add them to .gitignore file.
- [x] Do not commit inline comments. 
- [x] Use stickler for checks.

##### Other Requirements
- [x] Keep your code clean.
- [x] Do not commit debugging instructions

# Project Status :

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team !  

### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.

screen

Kindly recommended to check your bubble_sort method now it works not correct
bubblesort

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by sz16900** [comment]
Hi Anna!

Yes completely forgot to add a return statement to our main function... 🙈
We hope this is it! 🤞

**Comment by Anna-Myzukina** [comment]
### Nice job! Project looks! :100: 

## Status [Approved]


You have resolved all the issues!!!




#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding!

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
